export const S = Object.freeze({
  WELCOME: 'WELCOME',
  MAIN_MENU: 'MAIN_MENU',
  SERVICE_SELECTION: 'SERVICE_SELECTION',
  SERVICE_DETAILS: 'SERVICE_DETAILS',
  CONTACT_DETAILS: 'CONTACT_DETAILS',
  CONFIRMATION: 'CONFIRMATION',
  NEXT_ACTION: 'NEXT_ACTION',
  PRICING_MENU: 'PRICING_MENU',
  PRICING_RESULT: 'PRICING_RESULT',
  ORDER_ISSUE_TYPE: 'ORDER_ISSUE_TYPE',
  ORDER_DETAILS: 'ORDER_DETAILS',
  PARTNERSHIP_TYPE: 'PARTNERSHIP_TYPE',
  PARTNERSHIP_DETAILS: 'PARTNERSHIP_DETAILS',
  HANDOFF_CATEGORY: 'HANDOFF_CATEGORY',
  HANDOFF_ACTIVE: 'HANDOFF_ACTIVE',
  SUPPORT_MENU: 'SUPPORT_MENU',
  START_OVER_CONFIRM: 'START_OVER_CONFIRM'
});

export const QUESTION_STATES = new Set([S.SERVICE_DETAILS, S.CONTACT_DETAILS, S.ORDER_DETAILS, S.PARTNERSHIP_DETAILS]);
// States we never return to via BACK (they have side effects or are transient)
export const NON_RETURNABLE = new Set([S.PRICING_RESULT, S.START_OVER_CONFIRM, S.HANDOFF_ACTIVE, S.NEXT_ACTION, S.CONFIRMATION, ...QUESTION_STATES]);
